"""add projects table

Revision ID: b336f32fd92b
Revises: 4bfb9151df65
Create Date: 2026-02-04 10:15:37.101653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b336f32fd92b'
down_revision = '4bfb9151df65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_prevista', sa.Date(), nullable=True),
    sa.Column('minutos_estimados', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('minutos_estimados', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('horas_estimadas')

    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizada', sa.Boolean(), nullable=False))
        batch_op.drop_column('started_at')
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('finalizada')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_estimadas', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('minutos_estimados')
        batch_op.drop_column('color')
        batch_op.drop_column('project_id')

    op.drop_table('milestones')
    op.drop_table('projects')
    # ### end Alembic commands ###
